[tool.poetry]
name = "evnex-ha"
version = "0.2.5"
description = ""
authors = ["Brian Thorne <brian@thorne.link>"]

[tool.poetry.dependencies]
python = "^3.10"
homeassistant = "^2022.9.7"
evnex = "^0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
